#!/bin/bash

# the script is expected to live in the same directory
# as some of its datafiles
cd $(dirname $0)

IRM_tty=/dev/ttyUSB0		# the device the AVR is attached to
IRM_logdir=/var/local/power	# this is where we will accumlate data

# fetch user overrides for the IRM_xxxx variables
test -f config && . config

./read_ir -rv $IRM_tty 2>>/tmp/read_ir.log |
    ./ir_meterlog -v -d $IRM_logdir 2>/tmp/ir_meterlog.log

